### PR TITLE
shuffle serial list

### PR DESCRIPTION
**Pull request by zapion**
in term of reducing conflict for getting device, shuffle the serial list before get_device

### CODE REVIEW

**Comment by zapion** [comment]
@ShakoHo , @ypwalter  r?

**Comment by ypwalter** [comment]
I think it's a good idea. r+

**Comment by zapion** [comment]
Well the major issue here is
the list we shuffled actually push into a map later.
I'm not sure it works when using map.

**Comment by ypwalter** [comment]
I think we can just do a trial run on moztwqa-01 to see if it works.
However, we used map before already right? The only thing we changed here is just to shuffle the items.

**Comment by ypwalter** [comment]
Please be more specific in description next time.
I think you mean that you are not sure if the order will be changed in map structure, right?
(it works, just work in a different way.)

r-

from random import shuffle
a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
shuffle(a)
obj_map = {}
for item in a:
    obj_map[item] = item
for serial_key in obj_map.keys():
    print serial_key

I would get the same result all the time.

**Comment by ypwalter** [comment]
How about just do:
shuffle(list(device_obj_map.keys()))
in line 159.

**Comment by ShakoHo** [comment]
second with Walter, I also test in my local environment, the key will retrieve from device_obj_map.keys(), so shuffle(serial_list) doesn't help

**Comment by ypwalter** [comment]
from random import shuffle
    a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    shuffle(a)

    print a
    obj_map = {}
    for item in a:
        obj_map[item] = item
        print item

    print obj_map.keys()
    for serial_key in obj_map.keys():
        print serial_key

    arr = obj_map.keys()
    shuffle(arr)
    print arr
    for serial_key in arr:
        print serial_key

I think do a work-around near 159 to get the keys list, shuffle it, and it should work in a proper way.

**Comment by ShakoHo** [comment]
agree with Walter..

**Comment by zapion** [comment]
It's too outdated, open a new branch for further tracking.

**Pull request closed without merging**
